server:
  port: 8082
spring:
  application:
    name: customer

  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.105.189.141/EurekaServer/eureka/